name: Update Launch-Core Submodule
on:
  repository_dispatch:
    types: update
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.LAUNCH_ACCESS_TOKEN }}
          submodules: recursive
      - name: Update Launch-Core
        run: |
          git submodule update --init --recursive --checkout -f --remote -- "${{github.event.client_payload.module}}"
          git config --global user.name "RIT Launch Initiative"
          git config --global user.email "launchinitiative@rit.edu"
          git commit -am "update: ${{github.event.client_payload.module}}"
          git push

      - name: GNU Arm Embedded Toolchain
        uses: ryanwinter/arm-none-eabi-gcc@v2.0.4
        with:
          release: '10.3-2021.10' # The arm-none-eabi-gcc release to use.

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C ${{env.BUILD_TYPE}}
